name: Build
on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Setup JDK8
        uses: actions/setup-java@v3.10.0
        with:
          distribution: zulu
          java-version: 8
          cache: gradle

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.6

      - name: Build
        id: build
        run: ./gradlew build

      - name: Upload artifact
        if: steps.build.outcome == 'success'
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Artifact
          path: ./build/libs/*
          retention-days: 30

      - name: Publish
        if: steps.build.outcome == 'success' && github.ref == 'refs/heads/master'
        env:
          NexusUsername: ${{ secrets.SIRO256_NEXUS_USER }}
          NexusPassword: ${{ secrets.SIRO256_NEXUS_PASSWORD }}
          SigningKey: ${{ secrets.SIRO256_MAVEN_SIGNING_KEY }}
          SigningKeyPassword: ${{ secrets.SIRO256_MAVEN_SIGNING_KEY_PASSWORD }}
        run: ./gradlew publish
